name: Deploy Hexo
on:
  push:
    branches:
      - hexo-src-test # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Deploy
        run: |
          git config  --global user.name 'Topppy'
          git config  --global user.email 'Topppy@users.noreply.github.com'
          npm run deploy